build: false
platform:
  - x64

environment:
  COMPOSER_NO_INTERACTION: "1"
  ANSICON: '121x90 (121x90)'
  matrix:
    - PHP_VERSION: '7.2'
      COMPOSER_FLAGS: '--prefer-stable --prefer-lowest'
    - PHP_VERSION: '7.3'
    - PHP_VERSION: '7.4'

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\Composer\files -> composer.lock'
  - composer.phar
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\tools\php -> appveyor.yml

init:
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/ChadSikorra/ps-install-php/master/Install-PHP.ps1" -OutFile "Install-PHP.ps1"
  - ps: .\Install-PHP.ps1 -Version $Env:PHP_VERSION -Highest -Arch x64 -Extensions mbstring,fileinfo,openssl
  - echo zend_extension=php_opcache.dll >> C:\tools\php\php.ini
  - refreshenv
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar update %COMPOSER_FLAGS% --no-interaction --no-progress -vvv
  - php composer.phar info -D | sort

test_script:
  - vendor/bin/phpunit -c phpunit.xml.dist
