# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Building Require-Checker phar for release"

on:
  release:
    types: [published]

jobs:
    build:
        name: "Building Require-Checker phar"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4

            - name: "Install PHP"
              uses: "shivammathur/setup-php@2.28.0"
              with:
                  coverage: "none"
                  php-version: "8.2"
                  ini-values: memory_limit=-1, phar.readonly=0

            - name: "Import GPG Key"
              run: echo "$PRIVATE_KEY" | gpg --import
              env:
                PRIVATE_KEY: ${{ secrets.SIGNING_SECRET_KEY }}

            - name: "Install dependencies for build environment"
              run: "composer install --no-interaction --no-progress --no-suggest"

            - name: "Build and sign phar file via phing"
              run: "vendor/bin/phing phar-build phar-sign"

            - name: "Upload phar file artifact"
              uses: actions/upload-artifact@v3
              with:
                  name: composer-require-checker.phar
                  path: |
                    build/composer-require-checker.phar
                    build/composer-require-checker.phar.asc

            - name: Upload PHAR to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: build/composer-require-checker.phar*
                file_glob: true
                tag: ${{ github.ref }}
